[build]
  command = "npm install -f" # Or whatever your build command is

# This is the most important part - it ensures your API routes are properly handled
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# This ensures client-side routing works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
